# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# forward focus change event
set-option -g focus-events on

# vi is good
setw -g mode-keys vi

# set starting index 1
set -g base-index 1
setw -g pane-base-index 1

# enable mouse support
set -g mouse on

# mouse drag to copy to clipboard 
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel 'wl-copy'

# mouse release does not exit nor jump to bottom 
unbind 	-T copy-mode-vi MouseDragEnd1Pane
bind 	-T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe 'wl-copy'

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# split panes 
bind b split-window -h
bind v split-window -v
unbind '"'
unbind %

# vim selection and yanking
bind -T copy-mode-vi v    send -X begin-selection
bind -T copy-mode-vi C-v  send -X rectangle-toggle
bind -T copy-mode-vi V    send -X select-line
bind -T copy-mode-vi y    send -X copy-pipe-and-cancel 'wl-copy'
bind -T copy-mode-vi Y    send -X copy-pipe-and-cancel 'wl-copy'

# vim-like keys for splits and windows
bind v split-window -v
bind s split-window -b

# zellij like pane/window navigation
bind -n M-h if -F '#{pane_at_left}' 'previous-window' 'select-pane -L'
bind -n M-l if -F '#{pane_at_right}' 'next-window' 'select-pane -R'
bind -n M-j select-pane -D
bind -n M-k select-pane -U

# copy mode with Ctrl-a + Esc or Alt-v
bind -n M-v copy-mode

# Theme (alternatives in ~/.config/tmux/, e.g. catppuccin-mocha.conf)
source-file ~/.config/tmux/oxocarbon.conf

