# Prevent server exit without sessions
set -s exit-empty off

# Start counting windows and panes from 1
set -g base-index 1
setw -g pane-base-index 1

# Time betweeb leader combo and input key
set-option -sg escape-time 10

set-option -g focus-events on

set-option -g default-terminal "screen-256color"
set-option -sa terminal-features ',xterm-256color:RGB'

setw -g allow-rename off
setw -g automatic-rename off

set -g history-limit 20000
set -g buffer-limit 20

# Use xclip to copy and paste with the system clipboard (requires xclip)
bind C-c run "tmux save-buffer - | xclip -i -sel clip"
bind C-v run "tmux set-buffer $(xclip -o -sel clip); tmux paste-buffer"

# Set parent terminal title to reflect current window in tmux session 
set -g set-titles on
set -g set-titles-string "#I:#W"

# Enable mouse support
set -g mouse on

# Prompt to rename window right after it's created
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'

# Reload tmux configuration 
bind C-r source-file ~/.tmux.conf \; display "Config reloaded"

# Prefer vi style key table
setw -g mode-keys vi

# Custom theme based on Wombat
color_red="#E5786D"
color_yellow="#EAE788"
color_green="#AEE474"
color_black="#262626"
color_grey="#3C3C3C"
color_white="#E4E0D7"
color_blue="#8DBDFB"
color_purple="#3e3969"

set -g mode-style "fg=default,bg=$color_green"

# command line style
set -g message-style "fg=$color_green,bg=$color_black"

# status line style
set -g status-style "fg=$color_white,bg=$color_black"

# window segments in status line
set -g window-status-separator ""
separator_powerline_left=""
separator_powerline_right=""

# setw -g window-status-style "fg=$color_status_text,bg=$color_dark"
setw -g window-status-format " #I:#W "
setw -g window-status-current-style "fg=$color_black,bold,bg=$color_blue"
setw -g window-status-current-format "#[fg=$color_blue,bg=$color_black]$separator_powerline_left#[default] #I:#W# #[fg=$color_blue,bg=$color_black]$separator_powerline_right#[default]"

# when window has monitoring notification
setw -g window-status-activity-style "fg=$color_green"

# outline for active pane
setw -g pane-active-border-style "fg=$color_green"

# general status bar settings
set -g status on 
set -g status-interval 5
set -g status-position bottom
set -g status-justify left
set -g status-right-length 100

# Templates for statusbar widgets
wg_session=" #S "
wg_user_host="#[fg=$color_green,bg=$color_grey]#[fg=$color_black,bg=$color_green] #[fg=$color_white,bg=$color_grey] #(whoami)@#H"
wg_sysstat_mem="#[fg=$color_yellow,bg=$color_grey]#[fg=$color_black,bg=$color_yellow]󰍛 MEM #[fg=$color_white,bg=$color_grey] #{sysstat_mem}"
wg_sysstat_cpu="#[fg=$color_red,bg=$color_grey]#[fg=$color_black,bg=$color_red]󰻠 CPU #[fg=$color_white,bg=$color_grey] #{sysstat_cpu}"

set -g status-left " $wg_session"
set -g status-right "$wg_sysstat_cpu $wg_sysstat_mem $wg_user_host "

# Configure view templates for tmux-plugin-sysstat "MEM" and "CPU" widget
set -g @sysstat_mem_view_tmpl "#[fg=#{mem.color}]#{mem.pused}#[fg=default] (#{mem.used})"
set -g @sysstat_cpu_view_tmpl "#[fg=#{cpu.color}]#{cpu.pused}#[fg=default]"

# Configure colors for tmux-plugin-sysstat "MEM" and "CPU" widget
set -g @sysstat_cpu_color_low "$color_green"
set -g @sysstat_cpu_color_medium "$color_yellow"
set -g @sysstat_cpu_color_stress "$color_red"

set -g @sysstat_mem_color_low "$color_green"
set -g @sysstat_mem_color_medium "$color_yellow"
set -g @sysstat_mem_color_stress "$color_red"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'samoshkin/tmux-plugin-sysstat'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# To install TMUX plugin manager:  
# - git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# - in tmux, prefix + I to install plugins
run '~/.tmux/plugins/tpm/tpm'
