font_family  	JetBrainsMono Nerd Font

font_size 10.0

# Wombat theme

background            #1f1f1f
foreground            #e5e1d8
cursor                #bbbbbb
selection_background  #453a39
color0                #000000
color8                #313131
color1                #ff605a
color9                #f58b7f
color2                #b1e869
color10               #dcf88f
color3                #ead89c
color11               #eee5b2
color4                #5da9f6
color12               #a5c7ff
color5                #e86aff
color13               #ddaaff
color6                #82fff6
color14               #b6fff9
color7                #ded9ce
color15               #fefffe
selection_foreground  #171717

allow_hyperlinks yes
shell_integration enabled
allow_cloning ask

# wayland_titlebar_color system

