# Catppuccin Mocha — tmux theme
# Use with:  source-file ~/.config/tmux/catppuccin-mocha.conf

# Catppuccin Mocha Palette
color_rosewater="#f5e0dc"
color_flamingo="#f2cdcd"
color_pink="#f5c2e7"
color_muave="#cba6f7"
color_red="#f38ba8"
color_maroon="#eba0ac"
color_peach="#fab387"
color_yellow="#f9e2af"
color_green="#a6e3a1"
color_teal="#94e2d5"
color_sky="#89dceb"
color_sapphire="#74c7ec"
color_blue="#89b4fa"
color_lavender="#b4befe"
color_text="#cdd6f4"
color_subtext_1="#bac2de"
color_subtext_2="#a6adc8"
color_overlay_0="#6c7086"
color_overlay_1="#7f849c"
color_overlay_2="#9399b2"
color_surface_0="#313244"
color_surface_1="#45475a"
color_surface_2="#585b70"
color_base="#1e1e2e"
color_mantle="#181825"
color_crust="#11111b"

# command line style
set -g message-style "fg=$color_text,bg=$color_base"

# status line style
set -g status-style "fg=$color_text,bg=$color_base"
set -g status-left "#[fg=$color_blue]  #[fg=$color_text] #{server_sessions} #[default] "
set -g status-right "#[fg=$color_teal,bg=$color_base]󱘊 #[fg=$color_text,bg=$color_base] #(whoami)@#H#[default]"

set -g window-status-separator " "
set -g window-status-format "#[fg=$color_crust,bg=$color_surface_2] #I #[fg=$color_subtext_2,bg=$color_surface_0] #{p6:window_name} #[default]"
set -g window-status-current-format "#[fg=$color_crust,bg=$color_red] #I #[fg=$color_text,bg=$color_surface_1] #{p6:window_name} #[default]"

# Window tree view
set -g mode-style "fg=black,bg=$color_pink"
