-- mason's installed tools and running lsp servers
return {
	ensure_installed = {
		"lua-language-server",
		"stylua",
		"html-lsp",
		"css-lsp",
		"json-lsp",
		"tailwindcss-language-server",
		"prettierd",
		"typescript-language-server",
		"svelte-language-server",
		"gopls",
		"goimports",
		"goimports-reviser",
		"templ",
		"intelephense",
		"pretty-php",
		"docker-compose-language-service",
		"dockerfile-language-server",
		"ansible-language-server",
		"ansible-lint",
	},
	servers = {
		"lua_ls",
		"html",
		"cssls",
		"jsonls",
		"tailwindcss",
		"tsserver",
		"svelte",
		"tailwindcss",
		"gopls",
		"templ",
		"intelephense",
		"dockerls",
		"docker_compose_language_service",
		"ansiblels",
	},
}
