theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
text-width = 100
popup-border = "all"
true-color = true
end-of-line-diagnostics = "hint"

[editor.indent-guides]
character = "│"
render = true

[editor.file-picker]
hidden = false
parents = false

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
# display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
