[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "svelte"
language-servers = ["svelteserver", "typescript"]
formatter = { command = "prettier", args = ["--parser", "svelte"] }
auto-format = true

[[language]]
name = "json"
language-servers = ["vscode-json-languageserver"]
formatter = { command = "prettier", args = ["--parser", "json"] }
auto-format = true

